CREATE TABLE INGREDIENT (
  NAME VARCHAR(255),
  CONTAINS_LACTOSE BOOLEAN,
  VEGETARIAN BOOLEAN,
  VEGAN BOOLEAN,
  GLUTEN_FREE BOOLEAN
);

INSERT INTO INGREDIENT (NAME,CONTAINS_LACTOSE,VEGETARIAN,VEGAN,GLUTEN_FREE)
VALUES ('Eggs',FALSE,TRUE,FALSE,TRUE);
INSERT INTO INGREDIENT (NAME,CONTAINS_LACTOSE,VEGETARIAN,VEGAN,GLUTEN_FREE)
VALUES ('Bread',TRUE,TRUE,FALSE,FALSE);
INSERT INTO INGREDIENT (NAME,CONTAINS_LACTOSE,VEGETARIAN,VEGAN,GLUTEN_FREE)
VALUES ('Beef Patty',FALSE,FALSE,FALSE,TRUE);
INSERT INTO INGREDIENT (NAME,CONTAINS_LACTOSE,VEGETARIAN,VEGAN,GLUTEN_FREE)
VALUES ('Lettuce',FALSE,TRUE,TRUE,TRUE);
INSERT INTO INGREDIENT (NAME,CONTAINS_LACTOSE,VEGETARIAN,VEGAN,GLUTEN_FREE)
VALUES ('Yogurt',TRUE,TRUE,FALSE,FALSE);

-- Add constraints to every column of the INGREDIENTS table, you should use NOT NULL for some columns and unique for other(s)

